apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "detaaltoolbox.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: mongo
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "detaaltoolbox.selectorLabels" . | nindent 4 }}
  ports:
    - name: mongo-port
      port: 27017
      targetPort: 27017
