apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    {{- include "detaaltoolbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backendService.type }}
  selector:
    app: backend
    {{- include "detaaltoolbox.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.backendService.ports | toYaml | nindent 4 }}
