apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "detaaltoolbox.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "detaaltoolbox.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 30000
      targetPort: 30000
