apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
  {{- include "detaaltoolbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontendService.type }}
  selector:
    app: frontend
  {{- include "detaaltoolbox.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.frontendService.ports | toYaml | nindent 2 -}}