apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "detaaltoolbox.fullname" . }}-frontend
  namespace: {{ .Values.namespace.name }}
  labels:
  {{- include "detaaltoolbox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.deployment.replicas }}
  selector:
    matchLabels:
      app: frontend
    {{- include "detaaltoolbox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: frontend
      {{- include "detaaltoolbox.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: API_URL
          value: {{ .Values.frontend.deployment.apiUrl }}
        image: {{ .Values.frontend.deployment.image.repository }}:{{ .Values.frontend.deployment.image.tag }}
        name: frontend
        ports:
        - containerPort: 80
          name: http
        resources: {{- toYaml .Values.frontend.deployment.resources | nindent 10 }}
