apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: le-example-http
  # prettier-ignore
  namespace: {{ .Values.namespace.name }}
spec:
  acme:
    email: bellaalirachid@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # if not existing, it will register a new account and stores it
      name: example-issuer-account-key
    solvers:
      - http01:
          # The ingressClass used to create the necessary ingress routes
          ingress:
            class: traefik
