apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "detaaltoolbox.fullname" . }}-mongo-deployment
  labels:
  {{- include "detaaltoolbox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mongo.deployment.replicas }}
  selector:
    matchLabels:
      app: mongo
    {{- include "detaaltoolbox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mongo
      {{- include "detaaltoolbox.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.mongo.deployment.image.repository }}:{{ .Values.mongo.deployment.image.tag }}
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo-port
        resources: {{- toYaml .Values.mongo.deployment.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /data/db
          name: mongo-storage
      volumes:
      - emptyDir: {}
        name: mongo-storage
