apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "detaaltoolbox.fullname" . }}-mongo-deployment
  namespace: {{ .Values.namespace.name }}
  labels:
  {{- include "detaaltoolbox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mongo.deployment.replicas }}
  selector:
    matchLabels:
      app: mongo
    {{- include "detaaltoolbox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mongo
      {{- include "detaaltoolbox.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.deployment.image.repository }}:{{ .Values.mongo.deployment.image.tag }}
          ports:
            - containerPort: 27017
              name: mongo-port
          volumeMounts:
            - name: mongo-pvc
              mountPath: /data/db
      volumes:
        - name: mongo-pvc
          persistentVolumeClaim:
            claimName: mongo-pvc