apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  # prettier-ignore
  namespace: {{ .Values.namespace.name }}
spec:
  storageClassName: csi-cinder-high-speed
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # prettier-ignore
      storage: {{ .Values.mongo.pvc.size }}
