apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "detaaltoolbox.fullname" . }}-postgres-deployment
  namespace: {{ .Values.namespace.name }}
  labels:
  {{- include "detaaltoolbox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgres.deployment.replicas }}
  selector:
    matchLabels:
      app: postgres
    {{- include "detaaltoolbox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: postgres
      {{- include "detaaltoolbox.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.deployment.image.repository }}:{{ .Values.postgres.deployment.image.tag }}
          env:
            - name: POSTGRES_USER
              value: {{ quote .Values.postgres.deployment.env.postgresUser }}
            - name: POSTGRES_PASSWORD
              value: {{ quote .Values.postgres.deployment.env.postgresPassword }}
          ports:
            - name: postgres-port
              containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}
