apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace.name }}-postgres-service
  namespace: {{ .Values.namespace.name }}
  labels:
  {{- include "detaaltoolbox.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "detaaltoolbox.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres-port
      port: 5432
      targetPort: 5432