namespace:
  name: default
  ingressClassName: my-ingress-class

mongo:
  deployment:
    image:
      repository: mongo
      tag: latest
      pullPolicy: IfNotPresent
    replicas: 1

postgres:
  deployment:
    env:
      postgresPassword: postgres
      postgresUser: postgres
    image:
      repository: postgres
      tag: latest
      pullPolicy: IfNotPresent
    replicas: 1

backend:
  deployment:
    image:
      repository: rachiid007/dtt_backend
      tag: try_using_multiple_ingress
      pullPolicy: Always
      env:
        postgresHost: postgres-service
        mongoURL: mongodb://mongo-service:27017/de_taal_toolbox
    replicas: 1
kubernetesClusterDomain: cluster.local

frontend:
  deployment:
    image:
      repository: rachiid007/dtt_frontend
      tag: work_with_env_var
      pullPolicy: Always
    apiURL: ""
    replicas: 1

service:
  port: 80
